### ISSUE TITLE
can't convert ImageProcessing::Pipeline to String (ImageProcessing::Pipeline#to_str gives ImageProcessing::Pipeline)

### ISSUE THREAD

**Issue by ndbroadbent** [janko-m/image_processing#20]
After updating from `image_processing` version `0.4.5` to `0.10.2`, I'm getting this error:

```
can't convert ImageProcessing::Pipeline to String (ImageProcessing::Pipeline#to_str gives ImageProcessing::Pipeline)
```

in this code:

```ruby
include ImageProcessing::MiniMagick

...

image = resize_to_fill!(image, width, height, gravity: gravity)

...

versions[:resized] = File.open(image.path, 'rb')
```

I'm also seeing this warning:

```
[IMAGE_PROCESSING DEPRECATION WARNING] This API is deprecated and will be removed in ImageProcessing 1.0. Please use the new chainable API.
```

I think this crash is happening in `File.open(image.path, 'rb')`. What would be the correct fix for this?

**Comment by ndbroadbent** [comment]
Love the new chainable API! And `ruby-vips` looks great too, I might switch to that.

For anyone else who comes across this issue, here's I rewrote the code. First of all, don't `include ImageProcessing::MiniMagick` anymore.

```
image = ImageProcessing::MiniMagick.source(image).resize_to_fill!(width, height, gravity: gravity)
```

Thanks for this gem, it's great!

**Comment by janko-m** [comment]
@ndbroadbent The issue was that you've included  `ImageProcessing::MiniMagick` in the global namespace, which includes it into every class and module as well, including some `ImageProcessing` classes, and that messes things up with the new chainable API. If you perform the same code inside a class, it works correclty.

This was shown in the readme before, my apologies for that 😄. But please do switch to the new chainable API eventually, it should be very straightforward.
