### ISSUE TITLE
Right way to convert only the first page of the multipage PDF to JPEG with new Chainable API

### ISSUE THREAD

**Issue by incubus** [janko-m/image_processing#23]
Hi!

`source(file, page: page)` and [DeprecatedApi convert method](https://github.com/janko-m/image_processing/blob/master/lib/image_processing/mini_magick/deprecated_api.rb#L73) doesn't work. 

`source("#{file.path}[#{page}]")` works, but looks a little bit hacky. Thanks!

WBR,
Alexander

**Comment by janko-m** [comment]
The correct way is to pass `:page` to `#loader`:

```rb
ImageProcessing::MiniMagick
  .source(file)
  .loader(page: page)
  # ...
```

This is [documented](https://github.com/janko-m/image_processing/blob/master/doc/minimagick.md#loader), but the deprecated `#convert` implementation was broken after switching to the new API, as you said I was passing `:page` to `#source` instead of `#loader`. That happened because I didn't happen to have any tests for the deprecated `#convert`, so I added them now, fixed the deprecated `#convert`, and released a new image_processing version. But you should use the chainable API if you can.

**Comment by incubus** [comment]
Thanks!
