### ISSUE TITLE
Support GraphicsMagick

### ISSUE THREAD

**Issue by NARKOZ** [janko-m/image_processing#36]
http://www.graphicsmagick.org/

The API is almost identical to ImageMagick's.

**Comment by aried3r** [comment]
I can't speak for @janko-m of course, but official support was dropped three weeks ago. There's also a commit comment which shares more insight, HTH.

https://github.com/janko-m/image_processing/commit/4437199987dd65b8c139e2ad48ddde7d821d075a

**Comment by janko-m** [comment]
I decided to stop testing on GraphicsMagick mainly because it made it more difficult to maintain the test suite, as it added another layer when tracking assertion failures. It also made the tests run twice as long, because they needed to be run once for ImageMagick and once for GraphicsMagick.

However, I realized now that we can run GraphicsMagick tests only on Travis CI, which should make local development much easier. I will push that change now, as well as add instructions on how to use GraphicsMagick. Note that all ImageProcessing functionality already happens to work on GraphicsMagick.
