### ISSUE TITLE
Gif corruption fix

### ISSUE THREAD

**Issue by Chocksy** [janko-m/image_processing#8]
I tried to upload a gif using shrine and using resize_to_fill! made the gif corrupted as it was resized.

In order to fix this i had to make this method:

```ruby
  def process(io, context)
    case context[:action]
    when :store
      {
        original: custom_resize!(io, 920, 690),
        medium:  custom_resize!(io, 800, 600),
        thumb:  custom_resize!(io, 360, 270)
       }
    end
  end

  def custom_resize!(io, width, height)
    if io.content_type == 'image/gif'
      processed = with_minimagick(io.download) do |image|
        image.coalesce
        image.combine_options do |cmd|
          cmd.resize "#{width}x#{height}^"
          cmd.gravity "Center"
          cmd.background "rgba(255,255,255,0.0)" # transparent
          cmd.extent "#{width}x#{height}"
        end
      end
      processed
    else
      resize_to_fill!(io.download, width, height)
    end
  end
```

Is this the only way of doing this with the plugin? Just adding a block to `resize_to_fill!` exposes just the cmd not the image and `coalesce` does not work on the cmd.

Is it possible to expose the image too in that yield?

**Comment by janko-m** [comment]
In which way doesn't `#coalesce` work on the `cmd` object? The `MiniMagick::Tool` object implements `method_missing` which transforms all undefined methods into ImageMagick options, so calling `#coalesce` on it should work.

You can just process the image with `#coalesce`, and then pass it to `resize_to_fill!`, it will achieve the same result as your example:

```rb
file = io.download
with_minimagick(file) { |image| image.coalesce }
resize_to_fill!(file, width, height)
```

It's not possible to expose the `MiniMagick::Image` object in the yield of `#resize_to_*` methods, because it already yields a `MiniMagick::Tool` object, which by design isn't related to a specific `MiniMagick::Image` object (you can use it standalone).

**Comment by Chocksy** [comment]
It doesn't work in the way that it does not produce a gif that is not corrupted. But i'll go ahead and try the solution you provided as that is much more elegant and see if it works that way. 

Thanks! :D

**Comment by Chocksy** [comment]
Yep doing this works as expected:
```ruby
    file = io.download
    with_minimagick(file) { |image| image.coalesce } if io.content_type == 'image/gif'
    resize_to_fill!(file, width, height)
```

This does not work though:

```ruby
    file = io.download
    resize_to_fill!(file, width, height) do |cmd|
      cmd.coalesce if io.content_type == 'image/gif'
    end
```
